### ISSUE TITLE
[question] Arbitrary coordinates

### ISSUE THREAD

**Issue by opk12** [woheller69/omweather#1]
In the [F-droid app page](https://f-droid.org/en/packages/org.woheller69.omweather/) the first screnshot says `48.17° / 11.76°`. How do I have such an arbitrary position instead of a city? My municipality spans over ~10 km, so I am checking the weather on a small bordering municipality, which is reasonably near my house. This works but ideally I would set an arbitrary location.

**Comment by woheller69** [comment]
you need to switch on GPS. Then you can have GPS coordinates in 1st TAB. You will see a location button.
If you use the widget it will auto update position

**Comment by opk12** [comment]
Thank you!

**Comment by freecycler** [comment]
I'd like to second this request. I am sometimes interested in the weather for places other than my actual location, which is difficult to do if it is an obscure place not easily found by city search. For instance, planning before a trip. Or following up after the trip is completed and I am no longer there, so the GPS method would not work. And this might be wanted for more than just one location, so using only the first slot for several GPS locations I am not actually at doesn't really cover it.

I'd also like to tag them with a more memorable label than just the coordinates or city names, such as "Grandma's House", or "Joe's Cabin".
