### ISSUE TITLE
Swipe wochentag

### ISSUE THREAD

**Issue by leminsc8er** [woheller69/omweather#10]
Wunsch 
Swipe wochentag in app über swipe tageszeit.

**Comment by woheller69** [comment]
verstehe ich nicht

**Comment by leminsc8er** [comment]
Verständlich, also es gibt inapp das Feld wo man nach links und rechts swipen kann, um den wetterverlauf mit tageszeit zu sehen. Nach 24h springt logischerweise die Wochentagsanzeige über dem Feld mit den 3 Ansichten um.

Nun wäre es klasse, wenn man auch djese Wochenanzeige swipen könnte um den vorgang zu beschleunigen.

Vielleicht gibt es such noch andere komprimierte Ansichtsmöichkeiten um schneller mehr von den weiteren Tagen zu sehen.

**Comment by woheller69** [comment]
einfach auf den Wochentag klicken

**Comment by leminsc8er** [comment]
> einfach auf den Wochentag klicken
Dann hab ich da einen bug. Da passiert bei mir leider nichts.

Samsung xCover 4s/android 11

**Comment by woheller69** [comment]
In der Wochenübersicht auf einen Tag klicken geht nicht? Geht bei mir mit Android 6,10,11,12,13...

**Comment by leminsc8er** [comment]
Doch siehe edit.
Ich hab die verbindung erst spät wahrgenommen, danke dir!
