### ISSUE TITLE
Show loading indication instead of default "sunny weather"

### ISSUE THREAD

**Issue by Cwpute** [woheller69/omweather#100]
**Describe the bug**
When you open a city tab for which the weather wasn't already loaded, you get to see a bright sunny icon with 0°C no wind… which is incorrect, because it's just the default values for weather that isn't already loaded.

**How to Reproduce**
1. Set at least one location
2. Set your app to load weather data every hour
3. Wait for your weather data to expire
4. Go to your location tab and see default weather appear until the real weather is shown

**Expected behavior**
Do not show default weather values that don't mean anything, and display something that tells the user the data is updating.
For example: instead of having you default values be actually plausible things, have them display `-`, and don't show any weather icon. You could have a little toast message appear that says `Loading…` until the weather is loaded, or a circling animation like the refresh animation in many apps that pull data from the web.

**Environment (please complete the following information):**
 - App version: 3.1
 - Android version: 11

**Comment by woheller69** [comment]
no, if there is no data I get an empty white tab

**Comment by Cwpute** [comment]
I'll try to get you a screenshot

**Comment by woheller69** [comment]
I think I found what you mean. It does not happen when you add a new city and have not yet loaded data. It happens when you did not use a city for a long time. In this case there is still old data but no data for the current time.

**Comment by Cwpute** [comment]
well i can't seem to reproduce it, but i can assure you it did happen. i'll update this issue with screenshots and details if i ever come across it again.

**Comment by Cwpute** [comment]
sorry didn't see your last contribution ! it might be what you found as i don't browse the app every day.
