### ISSUE TITLE
Explanation for "update interval" option

### ISSUE THREAD

**Issue by Cwpute** [woheller69/omweather#101]
**Problem**
The update interval is only for when the app is already open, or for the widget if you have it set up. This is not clearly explained in the options and one can assume the app will update in the background.

**Suggested solution**
Provide a little explanation text under that option to say the app.never updates in the background and that this is for the widge only.

**Environment (please complete the following information):**
 - App version: 3.1
 - Android version: 11

**Comment by woheller69** [comment]
This is not the widget update intervall.

Intervall 1h means that the app will update data if you open that tab again after more than 1h since last update

**Comment by Cwpute** [comment]
Understood. I was mislead by this comment of yours: https://github.com/woheller69/omweather/issues/81#issuecomment-2134492770
I still think the option would benefit from this little explanation, as providing a time interval makes one think this is independent of any factor, like having the app open, or having fetched weather data less time ago than the set time interval.

**Comment by woheller69** [comment]
updating in background would not have any effect if you do not look at it.
The widget (and with it the first tab) will update in background or when you unlock device. 
This is controlled by Android mechanisms.
If you allow GPS for the widget it will also check for location changes about every 10 min and update in case of a major change.

**Comment by Cwpute** [comment]
Yes. Can you include a paragraph explaining that behavior under the time interval option ?

**Comment by woheller69** [comment]
I will rather remove that option as it mainly confuses people and does not make a lot of sense.
Open-Meteo weather models are updated once per hour so I might simply set a fixed value of 30 min

**Comment by Cwpute** [comment]
Oh yeah, definitely ! if models aren't updated that often, as far as i'm concerned, this is very much an acceptable solution 👍

**Comment by deedy5** [comment]
The widget updates fine in the background if you have disabled battery optimization for the app
