### ISSUE TITLE
Rain Radar Map issues when moving or zooming

### ISSUE THREAD

**Issue by mstammberger** [woheller69/omweather#102]
**Rain Radar Map ignores user's navigation operations**

I noticed several issues on using the Rain Radar Map which may have all the same reason. Therefore I will describe all of them in one report:

1. After zooming-in or -out (using two fingers, same when using the +/- buttons) the map ignores further navigation operations for approximately 1-2 seconds. This is very disturbing when I am zooming-in and then want to adjust the visible map section by moving.

2. While the Rain Radar "movie" is running the navigation (zoom and move) is nearly not possible! There are minimal timing gaps where the map is reacting on user's navigation request.

**Expected behavior**
The map shall be react immediately on user's navigation operations.

**Environment (please complete the following information):**
 - App version: v3.1
 - Android version: e-foundation /e/OS V2.3-s (Android 12)
 - Device: OnePlus Nord

**Comment by woheller69** [comment]
if I change this, we get other issues like flickering related to the used library

**Comment by mstammberger** [comment]
I understand that this behaviour is a side effect of the workaround to resolve the osmdroid flickering issue.
Nevertheless it is confusing to the user and closing the issue as "completed" is - in my opion - not really applicable.
I would keep the issue "open" and declare it as a "known issue" which will probably be fixed when a solution for the flickering issue (on which it depends) is available.
Keeping it open will additionally prevent other users from reporting it again.
