### ISSUE TITLE
[Feature request] Visualize rain forecast of next hour

### ISSUE THREAD

**Issue by mstammberger** [woheller69/omweather#103]
I don't know whether open-meteo provides this kind of data but it would be a great enhancement if there would be a rain forecast of the next hour visualized for a location. I know this feature from SeCuSo privacy-friendly-weather app where this is done by a row of rain drops (one drop represents 5 minutes):

![RainForecast_edit](https://github.com/user-attachments/assets/ff7a6380-f956-42c6-83fd-d35e14923558)

**Comment by woheller69** [comment]
I know, I wrote that part of the Secuso app.
Open-Meteo does not have hat data.
But the app already shows begin/end of next/current rain with 15 min resolution
