### ISSUE TITLE
[Feature Request] custom icons

### ISSUE THREAD

**Issue by MoonDragon-MD** [woheller69/omweather#105]
Hi thank you for your nice app, I used to use your other app “RadarWeather” after they changed API from 2.5 to 3 I switched to “Cirrus”.
I wanted to ask you if it is possible to integrate a group of external icons, for example I would like to have those from “[Chronus: MIUI Weather Icons](https://play.google.com/store/apps/details?id=com.dvtonder.chronus.miui)”, also LineageOs for weather widget you can set such external icons.

**Comment by woheller69** [comment]
Sorry, but I do not plan to work on this
