### ISSUE TITLE
[FR] Rain radar in a widget

### ISSUE THREAD

**Issue by Ypot** [woheller69/omweather#108]
Hi

I think it would be attractive to have in a widget the rain radar. 

Best regards

**Comment by woheller69** [comment]
unfortunately there is no simple way to achieve this

**Comment by woheller69** [comment]
I gave it a try. Unfortunately it is not possible to get the map below the radar image,
but we have the radar image a position marker and a distance marker.
So maybe it is helpful...
![radar_widget_preview](https://github.com/user-attachments/assets/8023d52e-a5e9-46ff-ac74-895a01dcc96d)

You can try it:
-Uninstall
-Remove .zip and install
[app-release.apk.zip](https://github.com/user-attachments/files/17538510/app-release.apk.zip)
