### ISSUE TITLE
Update setting is inverted

### ISSUE THREAD

**Issue by maver2** [woheller69/omweather#110]
**Describe the bug**
The function of the setting "nur manuell aktualisieren" (only update manually) is inverted from what one would expect, as far as the widget is concerned.

If the setting is deactivated (update autmatically, which was default) the widget will never be updated. If it is active (update manually), the widget is activated roughly by the current update interval.

**How to Reproduce**
1. add a widget to the desktop
2. Go to settings
3. leave 'only update manually' unchecked
4. set 'update interval' to 15 minutes (the minimum)
5. close the app, watch the widget
6. Wait for 16 minutes

**Expected behavior**
The widget should have been updated, visible from the time indicated

**Screenshots**
See attachment for the setting in German

**Environment (please complete the following information):**
 - App version: 3.2
 - Android version: 13
 - Device: Fairphone 3+
 
![Screenshot_20241009-163807_Cirrus_1](https://github.com/user-attachments/assets/040ec9bd-1a59-4c92-8c94-7f21a68a67a2)

**Comment by woheller69** [comment]
This feature only refers to updating location via GPS. 
Nur manuell... means the widget will not update location. You need to update location in app in this case

**Comment by maver2** [comment]
> This feature only refers to updating location via GPS. Nur manuell... means the widget will not update location. You need to update location in app in this case

Even then, there is a contradiction. What I want is the widget updates regularly, location is turned off, see screenshot. This is only achieved by "nur manuell aktualisieren " = true. Even worse if that only means location updates. How else can I have the regular widget updates? For me, this is a bug.

**Comment by woheller69** [comment]
The widget updates weather data about every 30min. Conrtolled by Android system.

**Comment by maver2** [comment]
So you doubt what I have written?

**Comment by woheller69** [comment]
Yeah. Widgets have been working for years.
Restart your phone.
