### ISSUE TITLE
WeatherWidgetAllInOne fallbacks to WeatherWidget after reboot

### ISSUE THREAD

**Issue by muziofg** [woheller69/omweather#111]
**Describe the bug**
WeatherWidgetAllInOne exists until the device isn't rebooted

**How to Reproduce**
Add the new widget "WeatherWidgetAllInOne"
Reboot the device
Instead of WeatherWidgetAllInOne I see WeatherWidget

**Expected behavior**
WeatherWidgetAllInOne should still be in its place

**Environment (please complete the following information):**
 - App version: 3.2
 - Android version: 14
 - Device: Lenovo Tab M10

**Comment by woheller69** [comment]
After first update of values which happens usually within a few seconds after boot it fixes itself.

But I found the bug and it will be fixed in next release
