### ISSUE TITLE
Location coordinates rename after refreshing 

### ISSUE THREAD

**Issue by oddball8983** [woheller69/omweather#112]
**Describe the bug**
After adding my default home location, I rename the coordinates i.e. Hamburg, after refreshing the weather data, coordinates are displayed again

**How to Reproduce**
1) add a new location
2) go to manage locations
3) click on coordinates, enter name and hit change
4) refresh weather data

**Expected behavior**
I want the app to save the names given to locations.

**Screenshots**

**Environment (please complete the following information):**
 - App version: v3.2
 - Android version: 14
 - Device: Redmi Note 13

**Comment by woheller69** [comment]
then you need to switch GPS to manual only. Location will then only be changed if you press the in app location button.
Otherwise the widget will do it
