### ISSUE TITLE
Manually adding a location seems impossible

### ISSUE THREAD

**Issue by barbaMimmo** [woheller69/omweather#113]
With location services switched off in both the phone and the app, I'm unable to add any location to the list.

1. Go to Manage Locations
2. Click on 'add new'
3. Write or paste geographical coordinates you obtained from an external map provider (e.g.: OsmAnd)
4. Notice there's no guidance on what format to use to write them :-(
5. Try every possible format, even exotic ones
6. Each an every time you get an error like 'No location was found corresponding to your input, etc.'
7. The app can't work without at least one location!

It should be very easy to insert geodata for a particular location, instead, and even to edit them.

Moreover, turning on GPS in both the phone and the app, in a phone with geoscrambling active, makes the app create and use a random location (mine was probably in Sudan) with --°/--° as its name, but there's no way to edit its coordinates.

 - App version: [Cirrus 3.4 from Fdroid]
 - Android version: [11, LineageOS 18.1]
 - Device: [Sony Xperia XZ3]

Thanks for the good job in creating and maintaining this app, which I'm willing to use in lieu of the apparently defunct Forecastie.
I provided this bug report as a form of collaboration.

Best regards
Mimmo

**Comment by barbaMimmo** [comment]
Thanks for the quick reply.

My fault I didn't guess I could simply enter a city name!
I was tricked by the fact the Italian translation asks you to literally "enter a position to add" and so I was convinced I should enter the coordinates, like in another app I was using.
So, now I have my city correctly recognized.

I still emphasize only the need for a better clarification of what to enter in the 'add location' dialogue, and also kindly request the possibility to enter geographical coordinates.

Keep up the good work!

**Comment by woheller69** [comment]
you can help by improving the translation

https://github.com/woheller69/omweather/blob/master/app/src/main/res/values-it/strings.xml

**Comment by barbaMimmo** [comment]
With pleasure!
I prefer to just propose here the two modifications I think it needs (strings N.40 and N.41):

40 <string name="dialog_add_label">Digita il nome di una località per aggiungerla dall'elenco che appare:</string>
41 <string name="dialog_add_no_city_found">Non è stata trovata alcuna città corrispondente. Seleziona uno degli elementi proposti nell\'elenco a tendina, oppure prova con un nome di capoluogo.  </string>

This could be not a literal translation (I have not seen the original English text), but N.40 now helps clarifying what the app expects you to write in the form, informing you that it wants the name of a town.
In this proposed revision, N.41 briefly clarifies that you ought to choose one of the proposed elements and suggests you to try with the name of a bigger city nearby instead, if a smaller one was not recognized.

Please consider to prolong the persistence of the warning corresponding to string N.41 a bit, since I notices it appears only for one or two seconds: not enough to read a two-rows phrase explaining what happened.
Double the time I think could be good.

I hope this meets your approval.
Best regards
Mimmo

**Comment by woheller69** [comment]
you can see the English original you change values-it to values in the link above

**Comment by barbaMimmo** [comment]
Thanks, I've just read it and noticed items don't necessarily have the same numbers.
N.46-en corresponds to N.40-it
N.47-en corresponds to N.41-it
They say "location", and so resulting quite confusing.
I think the concept I suggested for the Italian version could be adapted for the English one as well, if you liked it.

**Comment by woheller69** [comment]
the display duration of these strings cannot be extended. There are only SHORT and LONG available and we are using LONG ...
