### ISSUE TITLE
Box layout on smaller screens

### ISSUE THREAD

**Issue by Davi427** [woheller69/omweather#117]
**Describe the bug**

The box layout is not really usable on smaller screens. In portrait mode you have to scroll within these boxes and in landscape mode the two lower boxes are outside the screen.
Maybe this box mode is triggered too easily?

**How to Reproduce**
1. Go to 
5. 
Have any (somewhat small) screen that has more than 499 px width, look at portrait and landscape 

**Expected behavior**

Usable app without excessive scrolling

**Screenshots**

Landscape, vertically challenged 
![Screenshot_20241118-071440](https://github.com/user-attachments/assets/fabe8bb2-a895-4f19-adee-bca3059ce18c)

Portrait, boxes are horizontally challenged.
![Screenshot_20241118-071450](https://github.com/user-attachments/assets/aad70b02-b7cf-4751-8342-879b023976e8)

And this is at 500px minimum width, the boxes seem too small for the content
![Screenshot_20241118-072038](https://github.com/user-attachments/assets/5ff4e200-50fb-4c2d-9363-8dbd74d0de19)

**Environment (please complete the following information):**
 - App version: [e.g. v1.6] 3.4
 - Android version: [e.g. 10] 14
 - Device: [e.g. Google Pixel 4] Fairphone 5

**Comment by woheller69** [comment]
the grid layout is currently used for devices with a higher pixel number.
I might add an option in settings for this
