### ISSUE TITLE
City name replaced by numbers

### ISSUE THREAD

**Issue by danielbru1** [woheller69/omweather#118]
**Describe the bug**
Every few weeks, the name of the first city in the list of added cities is replaced by numbers (assumably its geo location)

**How to Reproduce**
Add a few cities
Wait a few weeks
The first city in the list doesn't show the name any more but the numbers (same on the widget)

**Expected behavior**
The City name is shown persistently. 

**Screenshots**
![Screenshot_20241202_080728_Cirrus](https://github.com/user-attachments/assets/db9a0403-3ddb-4f64-b17d-cd22b9c378a2)

**Environment (please complete the following information):**
 - App version: 2.9
 - Android version: 14
 - Device: Samsung Galaxy Ultra S21

**Comment by woheller69** [comment]
yes, when using GPS the first Tab is replaced with current location
