### ISSUE TITLE
Rain map only shown after display is touched

### ISSUE THREAD

**Issue by hurzl** [woheller69/omweather#119]
**Describe the bug**
The rain tiles are not triggered to be displayed after loading. You have to move or zoom the display. 

**How to Reproduce**
Open the rain map. The map is shown, but not the rain layer. Zoom or move the map to make it appear.

**Environment:**
 - App version: 3.5
 - Android version: 13
 - Device: s10

**Comment by woheller69** [comment]
I do not have the issue on any of my devices.
Can you try this version?

-uninstall
-remove .zip and install
[app-release.apk.zip](https://github.com/user-attachments/files/18038554/app-release.apk.zip)

**Comment by hurzl** [comment]
I don't want to lose all my settings. Is there a version I can install in parallel?

**Comment by woheller69** [comment]
ok. Try this, it has a different app id
[app-release.beta.apk.zip](https://github.com/user-attachments/files/18038671/app-release.beta.apk.zip)

**Comment by hurzl** [comment]
Thanks, it flickers more but that seems to make it work better.
