### ISSUE TITLE
Wunsch - weather by om ausblenden

### ISSUE THREAD

**Issue by leminsc8er** [woheller69/omweather#12]
Wunsch 
Widget und ggf inap info über "weather by om" optional ausblenden.
Cleane widgets sind immer schön.

**Comment by woheller69** [comment]
https://open-meteo.com/en/features#terms

You must include a link next to any location, Open-Meteo data are displayed like:

<a href="https://open-meteo.com/">Weather data by Open-Meteo.com</a>

**Comment by leminsc8er** [comment]
I know but it is not legal if user are optional invisble it ore show only inapp?
