### ISSUE TITLE
Can't find widget

### ISSUE THREAD

**Issue by maninthemiddle01** [woheller69/omweather#15]
**Describe the bug**
I can't find the widget. All others are there, also e.g. RadarWeather. I even uninstalled the latter and afterwards reinstalled omweather, still no widget.

**How to Reproduce**
I just installed the app

**Expected behavior**
Widget show up in widget section or in long press action of the app-starter.

**Environment (please complete the following information):**
 - App version: 1.2
 - Android version: Lineageos 18.1
 - Device: Samsung SM-A520F

**Comment by woheller69** [comment]
It is there for sure. Maybe reboot

**Comment by maninthemiddle01** [comment]
Reboot also didn't help

**Comment by woheller69** [comment]
I have no idea then. I am also on Lineageos (20)
But tested with Android 6, 10, 11, 12, 13 

It is essentially the same App as RadarWeather...

**Comment by maninthemiddle01** [comment]
I also don't know, RadarWeather is showing the widget

**Comment by woheller69** [comment]
Widgets also show on long press on the app icon. Have you installed the app on the SD card instead of internal memory?

**Comment by maninthemiddle01** [comment]
It did the trick to move it to the internal storage, thank you :)
