### ISSUE TITLE
Would it be possible to implement a rain radar for the next hour in the app and the widget?

### ISSUE THREAD

**Issue by maninthemiddle01** [woheller69/omweather#16]
It would be nice to have a rain radar for the upcoming 60 minutes like in RadarWeather. There this is shown in the widget and in the app as part of the tile with 
current weather informations.

![image16](https://user-images.githubusercontent.com/12028992/223990007-39d34d7f-1e6b-4ecc-a956-3e1c8cd0228a.png)
![image15](https://user-images.githubusercontent.com/12028992/223990016-d5d8c6fa-dc11-4ab9-80e8-b7ba8d61f901.png)

**Comment by maninthemiddle01** [comment]
Ah OK, thank you for your response. Too bad it's not available

**Comment by julonexus** [comment]
> There is a rain radar for 30min via the map symbol. The other data is not available from open-meteo

Maybe I'm wrong but it can be available : https://open-meteo.com/en/docs/dwd-api#latitude=47.42&longitude=6.86&minutely_15=rain

**Comment by woheller69** [comment]
in future we will have 15 minutely rain data. Now it is only in the DWD API but not yet in the gerneral API

**Comment by otosan0** [comment]
@woheller69 it looks like the rain radar forecast is gone. Is this related to the RainViewer API restrictions? Is there any alternative in sight?

**Comment by woheller69** [comment]
yes they removed clouds, forecast, restricted zoom, etc.
Currently there is no alternative
