### ISSUE TITLE
App ingores "update interval" option

### ISSUE THREAD

**Issue by janilowski** [woheller69/omweather#17]
The app is accessing my location and contacting an online service mutiple times per hour no matter my settings.
This not only uses batter power but also makes unnecessary connections which may have privacy implications since it's happening so often.

**How to Reproduce**
1. Install omWeather on an Android device.
2. Allow access to GPS.
3. Set "update interval" to an arbitrary value.
4. Monitor the connections the app makes.
5. The app connects to an online service and accesses the device location multiple times per hour.

**Expected behavior**
I assume the app should make as few connections as possible. I'd much prefer one or two connections per day and that's it. The app should respect the "update interval" setting.

**Screenshots**
![Screenshot_20230312-155706](https://user-images.githubusercontent.com/76809077/224553688-0f714f33-5cc6-49a7-8a03-425aa365edb4.png)
![Screenshot_20230312-155722](https://user-images.githubusercontent.com/76809077/224553690-33d92000-032d-4c36-a2bd-a275fd2d4c99.png)
![Screenshot_20230312-160932](https://user-images.githubusercontent.com/76809077/224553692-cc54693a-0951-4183-9762-12bd99f0253d.png)

**Environment (please complete the following information):**
 - App version: v1.2
 - Android version: 13
 - CalyxOS version: 4.6.1
 - Device: Fairphone 4 5G

**Comment by woheller69** [comment]
I guess you are using the widget. Then it updates roughly every 30 min and when you change location by a few kilometres.

**Comment by janilowski** [comment]
> I guess you are using the widget. Then it updates roughly every 30 min and when you change location by a few kilometres.
Oh, sorry, yes. I've failed to mention that...

> Otherwise the widget does not make any sense.
...but why does the widget need not to respect the update interval I've set manually?

**Comment by woheller69** [comment]
The first tab is contolled by the widget. The widget wakes up and updates every 30min if the screen is switched on.

If you want to save energy you should set location to manual only. This will remove the location listener running in background and also reduce Api calls.
Location csn then be changed in app with the button

**Comment by woheller69** [comment]
App widgets have a fixed update parameter 

     android:updatePeriodMillis

Blocking the http call after wakeup does not make sense.
A widget should not show wrong information.
