### ISSUE TITLE
V 1.2 says it is not connected to.the internet

### ISSUE THREAD

**Issue by datenbank-projekt** [woheller69/omweather#19]
Hi

V 1.2 says it is not connected to.the internet... i am using a virtual VPN as firewall'

**Comment by woheller69** [comment]
then maybe your VPN has an issue

**Comment by woheller69** [comment]
I am using isReachable()
https://developer.android.com/reference/java/net/InetAddress#isReachable(int)

**Comment by datenbank-projekt** [comment]
Thanks for the reply.
I uninstalled and reinstalled and the problem persists.
Reading your provided URL I agree it should detect the connection as it has.one: the app can search for a city and also display the rainradar but it fails to download weather data.due to the "no internet" error.

**Comment by woheller69** [comment]
Then probably your firewall blocks ICMP ECHO REQUESTs (Ping).

**Comment by peteman52** [comment]
I got the same problem with V1.3. No firewall, search for city and rainradar ok.

**Comment by woheller69** [comment]
Can you please try this? I am trying a different way to find if a device is online.
This problem sometimes also happens in my other apps for some users.
So maybe this is a solution:

Remove .zip from filename and install.
[app-release.apk.zip](https://github.com/woheller69/omweather/files/11283517/app-release.apk.zip)

**Comment by woheller69** [comment]
another small change.
[app-release.apk.zip](https://github.com/woheller69/omweather/files/11284138/app-release.apk.zip)

**Comment by datenbank-projekt** [comment]
Hi,
seems to work fine now on my RedMi Note 10 Pro. (tried your https://github.com/woheller69/omweather/issues/19#issuecomment-1515942244 version)

**Comment by stemy2** [comment]
The app keeps saying there's no internet connection even with vpn disabled.
