### ISSUE TITLE
Set precipitation measurements to Imperial

### ISSUE THREAD

**Issue by emacsomancer** [woheller69/omweather#21]
There does not seem to be a way to have precipitation measurements shown in inches/imperial.

**Comment by emacsomancer** [comment]
Hmm... that is a good point. I vaguely thought maybe display mms when it's below a certain amount, and then inches above, but that's just really messy.

**Comment by Yunier86** [comment]
I just installed the application, but it does not update me always puts me that I do not have an Internet connection, I really have a mobile data connection and other applications if they connect to each other RadarWeather, then why will onWeather not? For wifi if it works me, I must also say that I am in Cuba where the Internet connection is terrible, but as I said other applications if they work me.

**Comment by woheller69** [comment]
For internet issues - off topic here - try this apk.
Uninstall
Remove .zip and install
https://github.com/woheller69/omweather/files/11284138/app-release.apk.zip

**Comment by twikedk** [comment]
> For internet issues - off topic here - try this apk. Uninstall Remove .zip and install https://github.com/woheller69/omweather/files/11284138/app-release.apk.zip

Just tested it on an old Huawei Y5ii with Android 5.1 where I had the internet issue with the f-droid apk. The test version works like a charm.

**Comment by nmetrock** [comment]
Ignoring the new-off-topic replies above,,,,

Yes. I want to see Any metric readout in English Units.

You can s***talk all you want, but someone who has been born and raised on a system other than your own can definitely live and breathe Units that you don't understand.

Ie, using ur example:

".004 inches" makes more sense to me than some foreign computerized "0.1mm".

And yes I understand and can read both systems.

**Comment by woheller69** [comment]
Please feel free to implement a new option in settings and create a pull request

**Comment by woheller69** [comment]
[app-release.apk.zip](https://github.com/woheller69/omweather/files/13758269/app-release.apk.zip)

Try this:
- uninstall
- remove .zip and install
