### ISSUE TITLE
widget slightly clipped

### ISSUE THREAD

**Issue by xandro0777** [woheller69/omweather#23]
Hope I can attach a screenshot somehow? Ok .. that should be it:
![Screenshot_2023-04-03-13-00-42-55_b783bf344239542886fee7b48fa4b892](https://user-images.githubusercontent.com/43711649/229491806-3bc2b699-54ed-4781-bce8-1818ac65e2d0.jpg)

**Comment by woheller69** [comment]
click on it and resize it as needed

**Comment by xandro0777** [comment]
Sure, that works but I thought it was intended it would know its size?

**Comment by woheller69** [comment]
no, that depends on phone display
