### ISSUE TITLE
Pane widths

### ISSUE THREAD

**Issue by mvhulten** [woheller69/omweather#25]
The different panes are not using the full width but the screen is divided in two.  As a consequence, I only see a couple of days or hours.  Could the panes be configured to use the full width?

**Comment by woheller69** [comment]
I do not understand what you mean, can you add a screensot?

**Comment by mvhulten** [comment]
![omWeather-4panes](https://user-images.githubusercontent.com/6247934/232338588-d9e47704-5f97-414b-87f4-695e9ec39f57.png)

So here there are four panes/widgets distributed as 2x2.

Can this be done differently?  Specifically, can one use the full width of the window/screen (1x4)?

**Comment by woheller69** [comment]
This grid layout is used on devices with larger screens. You can rotate the device by 90° to use your screen better

**Comment by mvhulten** [comment]
The reason is that I would like to see an overview of the week (or about), without the need of scrolling.

**Comment by mvhulten** [comment]
It looks fine on smaller displays.  7 inch is just a bit of an in-between size.
