### ISSUE TITLE
"no network" error after latest update from F-Droid

### ISSUE THREAD

**Issue by xandro0777** [woheller69/omweather#26]
Updated from F-Droid today, app completely stopped working with mentioned error in a toast (mobile network, didn't try wifi yet). The widget displayed 0°K for the next 10 hours or so and the app didn't work either.

Have always Netguard activated and omweather worked fine with it before the update. Now deactivated Netguard and it works again. Reactivated Netguard - and it still works.

Ok, that is probably the weirdest bug report in a pretty long time but it happened like that ;(

**Comment by xandro0777** [comment]
Now, automatic update for the widget is broken. Set to 30 minutes. Manual update works. Had this sometimes in the previous version as well. Despite that battery usage indicates there must have been some activity, shows the same battery usage like gas prices.

Both Radarweather and Gas prices don't have this issue, all 3 have the same permissions and no special battery tweaks

**Comment by woheller69** [comment]
sometimes Android forgets updating its widgets. Restart the phone. Or remove the widget and place it again.

**Comment by xandro0777** [comment]
Persistently happens with just this one?
