### ISSUE TITLE
Widget  background transparency

### ISSUE THREAD

**Issue by cassio-tav** [woheller69/omweather#29]
This is a feature request aiming to improve user experience. A transparent background will allow for better integration of the widget into the user's home screen.

**Comment by woheller69** [comment]
If the widget background is completely transparent it depends on the phone background if the items are visible at all. Therefore I am using this semi-transparent background

**Comment by woheller69** [comment]
Try this, transparency can be set in settings, color will stay as it is.
[app-release.apk.zip](https://github.com/user-attachments/files/16962453/app-release.apk.zip)

Uninstall
Remove .zip and install
