### ISSUE TITLE
Broken widget

### ISSUE THREAD

**Issue by hacknorris-aka-penguin** [woheller69/omweather#32]
Its stuck on 42°C and doesnt show temperature :( ![](https://i.imgur.com/YdBUK2D.jpg)

**Comment by woheller69** [comment]
reboot your phone

**Comment by hacknorris-aka-penguin** [comment]
tried. worked for a second but after that it went back to displaying 42°C/42°C ...

**Comment by hacknorris-aka-penguin** [comment]
tried everything from list and nothing... not optimized battery, constantly in bg, was rebooting hone, removing and adding widget - once shown but only for a second... like it was blocked by app itself to get info..

**Comment by woheller69** [comment]
does app update the data?
What is your OS?

**Comment by woheller69** [comment]
do you have a battery saver?

**Comment by hacknorris-aka-penguin** [comment]
no i dont have battery saver. device is samsung m33 with custom launcher. will see if thats an issue cause for the now its the only thing i might have wrong...

**Comment by hacknorris-aka-penguin** [comment]
yea, launcher was an issue...
