### ISSUE TITLE
date missing

### ISSUE THREAD

**Issue by WagnerGMD** [woheller69/omweather#38]
Hello,
I'm wonder if you can add the date ? Because from my point of view, it will be a little improvement.
As we can see on [this picture](https://f-droid.org/repo/org.woheller69.omweather/en-US/phoneScreenshots/01.png), it's **"saturday"** but we don't have the date.
With the latest update, the people can choose a range (between 8  or 16 days) that's why it could be the current week (unless it's the next week).
Kind regards.

**Comment by woheller69** [comment]
You can try this apk.

Uninstall
Remove .zip and install

[app-release.apk.zip](https://github.com/woheller69/omweather/files/11719701/app-release.apk.zip)

**Comment by woheller69** [comment]
->V1.7
