### ISSUE TITLE
Precipitan VS Snow VS Rain

### ISSUE THREAD

**Issue by dromatriptan** [woheller69/omweather#4]
Greetings,

I stumbled on to your app through f-droid and I'm floored at how feature rich it is... And OMG ad-free!

I only had a handful of suggestions:

1. Maybe offer a way to distinguish between rain and snow? I saw the API provides values for these in addition to precipitation.
2. Provide conversion from mm to inches for us 'muricans 😂
3. Provide some sort of chart and icon legend to help understand the data 🥴

**Comment by woheller69** [comment]
1. they simply multiply precipitation by 7 to get snow height. Not a real benefit.
2. Do you really want to see 0.1mm in inches? You better get used to a modern unit system :-)
3. whats unclear?

**Comment by dromatriptan** [comment]
1. oh, ha ha. Thanks for this - makes it easy now.
2. Yea, you're right. It was worth a try 😁
3. So, I'm guessing that the red line is the high temp, the blue line is the low temp, and the blue bars is precipitation. What I'm unclear on is the gray area between the lines.

Other than that, buying you a coffee cause you rock.

**Comment by dromatriptan** [comment]
Ahh, thank you!
