### ISSUE TITLE
Poor readability in main weather screen due to low contrast

### ISSUE THREAD

**Issue by Percy90478** [woheller69/omweather#40]
In both light and dark mode, readability of the main screen is poor due to low contrast of text and background.

In light mode, its dark blue text on light blue background.
In dark mode, its grey text on black background.

This is not ideal. Please use colors that provide more contrast. And/or use a heavier or bold font.

**Comment by woheller69** [comment]
if you have problems you can use Android accessibility settings and e.g. switch to high contrast there

**Comment by Percy90478** [comment]
[Contrast ratio in Dark mode is only 3.09](https://app.contrast-finder.org/result.html?foreground=rgb%28102%2C102%2C102%29&background=rgb%2824%2C24%2C24%29&ratio=4.5&isBackgroundTested=false&algo=Rgb&lang=de) whereas [Web Content Accessibility Guidelines (WCAG) 2.0](https://www.w3.org/TR/WCAG20/#visual-audio-contrast-contrast) recommend ratio of >4.5

**Comment by woheller69** [comment]
I made a few small changes in dark mode.
You can try it.

Uninstall
Remove.zip and install

The color scheme is quite difficult. A small change in one place causes a problem in another place...
[app-release.apk.zip](https://github.com/woheller69/omweather/files/11787240/app-release.apk.zip)

**Comment by Percy90478** [comment]
Thank you! It's just a slight difference, but I'll try to go with it.
