### ISSUE TITLE
Rain prediction showing (-) value

### ISSUE THREAD

**Issue by twikedk** [woheller69/omweather#41]
**Describe the bug**
What I see is the rain prediction shows (-) value mm.
I could imagine it is somehow the weather API causing the issue.

**Screenshots**
![1 Screenshot_20230615-120046](https://github.com/woheller69/omweather/assets/24204069/b8347d2e-ce92-40d7-b74e-96f809b7a36e)

![2 Screenshot_20230617-160722](https://github.com/woheller69/omweather/assets/24204069/fd4914c7-ead8-42a3-b8d0-214fa156fbb3)

**Environment (please complete the following information):**
 - App version: v1.8
 - Android version: 10 & 12
 - Device: Huawei and Motorola

**Comment by woheller69** [comment]
Interesting, I never had this. If you see it again you could check the API directly here

https://open-meteo.com/en/docs

Select location and Precipitation (rain + showers + snow)

**Comment by woheller69** [comment]
If the bug is in the API, file it here

https://github.com/open-meteo/open-meteo

**Comment by woheller69** [comment]
Filed bug at open-meteo

https://github.com/open-meteo/open-meteo/issues/375

**Comment by twikedk** [comment]
I just tried to check the API on 26/6-23 for my area (55.95/8.51) the data for the API is not the same as shown on omWeather. Nothing on the API is shown as (-) but  4 out of 6 is on omWeather.

![Screenshot_2023-06-25_18-07-47](https://github.com/woheller69/omweather/assets/24204069/d8e3002b-f175-4559-8071-553e3e547d6b)

![Screenshot_20230625_180719_org woheller69 omweather](https://github.com/woheller69/omweather/assets/24204069/648300a0-28d3-4f32-8710-f696d885b242)

**Comment by woheller69** [comment]
https://api.open-meteo.com/v1/forecast?latitude=55.95&longitude=8.50&hourly=precipitation

The API does show the negative values for your location

I am using precipitation, which is the sum of all

**Comment by twikedk** [comment]
Sorry I had only chosen rain and showers, now I also see the API return negative values.

**Comment by woheller69** [comment]
Should be ok now. open-meteo fixed it.
