### ISSUE TITLE
Feels-Like Temperature (Apparent Temperature)

### ISSUE THREAD

**Issue by tinxx** [woheller69/omweather#42]
Would it be possible to display the additional `apparent_temperature` in the app and widget(s)?

> apparent_temperature | Instant | °C (°F) | Apparent temperature is the perceived feels-like temperature combining wind chill factor, relative humidity and solar radiation

[src](https://open-meteo.com/en/docs)

**Comment by woheller69** [comment]
I might add a switch to EITHER show temperatue (hourly + day min max) OR apparent temperature

**Comment by woheller69** [comment]
But unfortunately the API does not have apparent temp for current weather

**Comment by woheller69** [comment]
This test version has a switch to change between "normal temperatures" and "feels-like temperatures"
Then all temperature values are "feels-like"

Uninstall
Remove .zip and install

[app-release.apk.zip](https://github.com/woheller69/omweather/files/11878715/app-release.apk.zip)

**Comment by tinxx** [comment]
Thank you, @woheller69, it is definitely a nice feature!

When looking at the test build, I also added both widgets and noticed that the 3×2 widget seems not to display the *feels like* temperature. Is that the case? The 3×1 widget seems to be fine though.

You wrote that the API does not provide apparent temperature for current weather. Is that the reason? And if so: why is the in-app value different from the one displayed in the 3×2 widget?

However, I am not sure that I would use the option like it is now. I would much prefer to see both values at the same time.

**Comment by woheller69** [comment]
Thanks for testing. My fault. 
Current weather does not provide the data but Open-Meteo anyway uses the forecast for the current hour as current weather.
So I am taking current weather from forecasts now.

I forgot to change that in the widget.

Here is an updated version.

I am also not sure yet if I will use it but the probability is high. Currently testing. 
Why care about "real" temperature, in the end it is only relevant how it feels like...
[app-release.apk.zip](https://github.com/woheller69/omweather/files/11898017/app-release.apk.zip)

**Comment by tinxx** [comment]
Seems to work now, thanks!
