### ISSUE TITLE
[Feature request] Layout options

### ISSUE THREAD

**Issue by eleius** [woheller69/omweather#44]
Hello and thanks so much for this app. After trying many weather apps I finally settled with this one. Not only it's well done and easy to use, but I also like how Open Meteo doesn't require API keys and using Rain Radar is optional.

I wanted to ask if it would be possible to allow choosing how the weather "boxes" (daily, weekly, chart, etc) are arranged: on my phone they're on a single column, one below the other, while on my tablet they're arranged on 2 columns (like in the screenshots you have here on github.) My tablet however is not large enough so I find those very difficult to read.

It would be great if it was toggleable (1 or 2 column layout.)

On a side note I think it would be useful if humidity (RH) value could be optionally made visible in the weekly view - not sure if it can be done.

Thanks again for your work!

**Comment by woheller69** [comment]
will again think about it.

RH is not available for weekly view from Open-Meteo
