### ISSUE TITLE
Request: Icon legend

### ISSUE THREAD

**Issue by jackthebean** [woheller69/omweather#45]
While most of the icons are self explanatory it would still be helpful to have a way to see all the icons and what they represent.
Otherwise great, thanks.

**Comment by woheller69** [comment]
in this directory you can find all icons named wmo_code_xy....

https://github.com/woheller69/omweather/tree/master/app/src/main/res/mipmap-xhdpi

where xy is the weather code

![weather_codes](https://github.com/woheller69/omweather/assets/68678880/853ccf42-8c8e-4572-8ef7-d72a1cc265bf)
