### ISSUE TITLE
omWeather and Breezy Weather show different forecast

### ISSUE THREAD

**Issue by bege10** [woheller69/omweather#46]
When in Breezy Weather the weather service is set to Open Meteo it shows a different forecast for the same places than omWeather. How come?
https://github.com/breezy-weather/breezy-weather/discussions/438

**Comment by woheller69** [comment]
you can compare directly with Open-Meteo here:

https://open-meteo.com/en/docs

**Comment by bege10** [comment]
Thank you for the open-meteo link.

This is what I see right now. The differences are only slight now, in the last weeks with rapidly changing weather they were bigger. This shows differences in temperature. When it was raining in the last days there were differences also.

![Screenshot_20230903-154008_omWeather](https://github.com/woheller69/omweather/assets/1184237/12bee5af-d2e8-4ed2-bf80-80a9174897bc)
![Screenshot_20230903-154036_Breezy Weather](https://github.com/woheller69/omweather/assets/1184237/c87d83cb-6f51-4a6d-9d61-afe5ce0f9d6b)
![Screenshot_20230903-154053_Breezy Weather](https://github.com/woheller69/omweather/assets/1184237/fa3cc4d1-8160-4d65-9163-5700de78b825)

**From the Open Meteo website:**

![Screenshot_334](https://github.com/woheller69/omweather/assets/1184237/4cae001f-b8dd-4c1f-9230-0f1435146051)

**Comment by woheller69** [comment]
Maybe the coordinate is not exactly the same. I do not modify these values

**Comment by bege10** [comment]
In all three cases I entered "Hitzacker". Is this an issue of the apps or of Open Meteo that this may result in different coordinates?

**Comment by woheller69** [comment]
That depends on how the apps resolve the location.

**Comment by woheller69** [comment]
you can switch off rounding in omWeather to see original data

**Comment by bege10** [comment]
I switched on rounding to better compare with Breezy Weather. And without rounding the differences remain. See here:
https://github.com/breezy-weather/breezy-weather/discussions/438#discussioncomment-6897603

**Comment by bege10** [comment]
> That depends on how the apps resolve the location.

I see. I thought that does Open Meteo in all three cases.

**Comment by woheller69** [comment]
It seem the issue has been resolved in the other thread
