### ISSUE TITLE
Rotation clears selected city

### ISSUE THREAD

**Issue by littlecd** [woheller69/omweather#49]
**Describe the bug**
Select a city in Manage Locations and rotate device. The location in map becomes invalid. 

**How to Reproduce**
1. Go to Manage Locations
2. Click on Add
3. Specify city name
4. Rotate device

**Expected behavior**
The location persists in the map

**Screenshots**
Before rotation
<img width="313" alt="Screen Shot 2023-09-10 at 5 09 08 PM" src="https://github.com/woheller69/omweather/assets/144590216/97324340-9579-4874-8c7e-5aa9ed959333">

After rotation
<img width="597" alt="Screen Shot 2023-09-10 at 5 09 18 PM" src="https://github.com/woheller69/omweather/assets/144590216/3f43aabd-e223-4eda-8f09-ce4c55da7815">

**Comment by woheller69** [comment]
Don't rotate while adding a location
