### ISSUE TITLE
Precipitation Units Snow vs. Rain

### ISSUE THREAD

**Issue by gmogol** [woheller69/omweather#5]
I think the units of precipitation for snow is incorrect. I'm not sure if this is on open meteo API's side or app's side. My understanding is that snow precipitation units are given in cm, but rain precipitation is given in mm. Currently, the weather app shows mm for both of them.
The screenshots show this bug in play. It snowed 1cm at 22:00 where I was, not 1mm. In the second screenshot I compare the app's values with the values from open meteo api, which correctly produces cm instead of mm.

I'm happy to provide the details of my location in private but I don't think this is necessary.

![Screenshot_20230227-223605~2](https://user-images.githubusercontent.com/10942319/221990951-43795b0e-dcc4-4b20-b72c-66b0452f0bad.png)
![Screenshot_20230227-224028~2](https://user-images.githubusercontent.com/10942319/221990971-0381a5a6-f0be-4015-ac8e-15de6fef3ee6.png)

**Comment by woheller69** [comment]
You need to look at precipitation_sum which is the liquid equivalent. The app does not show snow height.

**Comment by woheller69** [comment]
![Screenshot_20230301-062530_FOSS Browser](https://user-images.githubusercontent.com/68678880/222052838-852e24bb-f6e7-4c0d-a048-28b7720d8f6d.jpg)

**Comment by gmogol** [comment]
I understand that the precipitation is the sum of all precipitation (rain,showers and snow). What I was trying to express is the following:

Looking at the forecast below, on Friday I see that it's going to be snowy and it shows me that the precipitation is going to be 13.9mm ~ 1.4cm. Taking this as the face value, I conclude that it's going to be a very mild snow in fact almost no snow. However, the reality is that there's going to be 14cm of snow, which is quite a lot of snow. Does it makes sense what I was trying to get at? It's very confusing when you're expecting 1cm of snow but you in fact get 10cm of it.

![Screenshot_20230301-140334~2](https://user-images.githubusercontent.com/10942319/222240673-d7f597ac-1b75-4fc2-a647-0ba16d3e82db.png)

**Comment by gmogol** [comment]
I think I'm really failing to get the point across. While what you are displaying might be technically correct, it's confusing and it's not what you expect it to be. When I look at a weather app I don't expect it to give me snow precipitation in the units of equivalent liquid precipitation. I didn't even know such a thing existed before I reported this bug. In other words, it would be more useful to show snow depth because most people would expect to see that.

**Comment by woheller69** [comment]
You can try this. I added an options in settings.
If activated instead of using precipitation value it sums up rain, showers, and snowfall (x10 to get it in mm), so it will give the precipitation "height"(?) instead of water equivalent.

-Uninstall old version
-remove .zip and install

[app-release.apk.zip](https://github.com/woheller69/omweather/files/10870063/app-release.apk.zip)

**Comment by woheller69** [comment]
have you tried it?

**Comment by gmogol** [comment]
I haven't but I will today!
