### ISSUE TITLE
Rain Radar disappears when rotating device

### ISSUE THREAD

**Issue by littlecd** [woheller69/omweather#50]
**Describe the bug**
Rain Radar disappears when rotating device

**How to Reproduce**
1. Go to Rain Radar
2. Rotate device

**Expected behavior**
Rain Radar persists there

**Screenshots**
Before rotation
<img width="311" alt="Screen Shot 2023-09-10 at 5 16 45 PM" src="https://github.com/woheller69/omweather/assets/144590216/3239b5c3-1ae8-4bca-bacb-9ff7c7f19b4d">

After rotation
<img width="599" alt="Screen Shot 2023-09-10 at 5 16 53 PM" src="https://github.com/woheller69/omweather/assets/144590216/31daef08-d74a-431c-90bd-02278b5d4ccb">

**Comment by woheller69** [comment]
Just open it again
