### ISSUE TITLE
Wrong weather symbol

### ISSUE THREAD

**Issue by jackthebean** [woheller69/omweather#51]
**Describe the bug**
Wondering if latest version has ug for hourly and day weather icon.  Last week was very sunny and hot. Om showed reasonable temp, wind etc but only ever showed total cloud for during the day.  Multiple other apps correctly showed day and hours as sunny.

**How to Reproduce**

Use the app. 

**Expected behavior**
Accurate weather icon. 

**Screenshots**

**Environment (please complete the following information):**
 - App version: v2. 0
 - Android version: 10
 - Device: Honor View 20

Thanks

**Comment by woheller69** [comment]
Weather services always show worst condition.
There is an option in settings to reanalyze the hourly forecasts
