### ISSUE TITLE
Wrong Layout - not readable 

### ISSUE THREAD

**Issue by Moosbueffel** [woheller69/omweather#55]
Icon & text in the widget are on top of each other. I just installed current version from f-droid. Would like it, cause it is not overloaded and well designed.

![IMG_20230925_100926](https://github.com/woheller69/omweather/assets/7726457/cd971da6-9f43-4a55-a494-8fd36386933f)

The same,with the other small widget 

I'm using XIAOMI Poco with MIUI Global 14.0.4 and Android 13.

**Comment by woheller69** [comment]
Just click on widget and increase size
