### ISSUE TITLE
GPS location doesn't work

### ISSUE THREAD

**Issue by Shikogo** [woheller69/omweather#58]
**Describe the bug**
When I run the app from my device, and I try to tap the location button, it just blinks forever and my location stays at Null Island. All location permissions are given.

**Environment (please complete the following information):**
 - App version: 6.2 through F-Droid
 - Android version: 12
 - Device: Redmi Note 9 Pro

**Comment by woheller69** [comment]
Then your device has a bad GPS. It blinks until a location is found. Go outside to speed up.

**Comment by Shikogo** [comment]
You are correct, my bad. Thank you!
