### ISSUE TITLE
wrong layout with RTL

### ISSUE THREAD

**Issue by ninmba** [woheller69/omweather#59]
Hello

OS: Android 11
System Language: Arabic
Results: omweather shows wrong layout in some parts

![Screenshot_1](https://github.com/woheller69/omweather/assets/40123526/ebd63424-489a-4317-90b4-54d2cc3d64f2)

![Screenshot_2](https://github.com/woheller69/omweather/assets/40123526/600bc366-f695-4893-8221-9c8865a3ea70)

**Comment by woheller69** [comment]
Please try this.

-Uninstall
-Remove .zip (just rename) and install

I don´t know what happens to the date. It should automatically be formatted according to your locale
I switched off RTL for some graphs and for the day widget.
[app-release.apk.zip](https://github.com/woheller69/omweather/files/12907850/app-release.apk.zip)
