### ISSUE TITLE
Using custom api URLs generated on open-meteo?

### ISSUE THREAD

**Issue by jult** [woheller69/omweather#6]
How does one enter this? 
https://open-meteo.com/en/docs#latitude=52.4276&longitude=4.9711&hourly=soil_temperature_0cm,soil_temperature_6cm,soil_moisture_1_3cm&models=ecmwf_ifs04,icon_seamless&daily=temperature_2m_max,temperature_2m_min,uv_index_max,precipitation_hours,precipitation_probability_max,windgusts_10m_max,winddirection_10m_dominant&timezone=Europe%2FBerlin
I prefer to use ICON model info, where to set this?

**Comment by woheller69** [comment]
not possible to select inside the app. But probaply open-meteo will use ICON anyway for your region
