### ISSUE TITLE
[Feature Request] Option to send weatherdata to Gadgetbridge

### ISSUE THREAD

**Issue by Foexle11** [woheller69/omweather#60]
Heyya,
Thank you for making this fantastic weather-app. I would love to see you add an option, for sending the weather-data to the app Gadgetbridge, so the users would be able to see the weather on the smart-devices. If it helps, heres a link to Gadgetbridges dokumentation: https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Weather .
Thanks for considering, have a nice day c:

**Comment by woheller69** [comment]
I will not support this, as I have no such device.

I would rather suggest that someone takes the source from omWeather and create a simple app which only acts as provider for Gadgetbridge.

Remove all activities besides ManageLocations
allow only 1 city
add an alarm receiver which wakes up every hour or so, fetches weather data and broadcasts to Gadgetbridge
