### ISSUE TITLE
Dynamic Location

### ISSUE THREAD

**Issue by RJGhugo** [woheller69/omweather#61]
Cities can be added to the list of the "weather forecast" or the "Spritpreise" but how can I add a "dynamic" location based on my GPS informations?

 Thanks.

**Comment by woheller69** [comment]
allow GPS in app settings and use the widget

**Comment by RJGhugo** [comment]
Thank you.

Reinstalled the omWeather app on the smartphone and the tablet.

About 10-15 minutes after the first GPS search the app found the location. OrganicMaps is finding the GPS location within some seconds...

**Comment by woheller69** [comment]
You can update immediately via the location button in the app. The widget checks location about every 10min

**Comment by RJGhugo** [comment]
Works fine on the smartphone. But not on the tablet with wifi only.

**Comment by woheller69** [comment]
it is not related to wifi. Just depends on GPS. Maybe GPS of your tablet does not work indoors.
omWeather does not use network provider, only GPS for privacy reasons.

**Comment by RJGhugo** [comment]
Thank you very much!
This was the problem/solution: go outdoor and catch gps...
