### ISSUE TITLE
Add location: Menu of location proposals can't be scrolled


### ISSUE THREAD

**Issue by uli-on** [woheller69/omweather#63]
**Describe the bug**
In portrait format, the location proposals menu can not be scrolled. So, for non-uniquely named locations there's often no opportunity to be selected.

**How to Reproduce**
- Use a small device like a smartphone in portrait format
- Open the Manage Locations screen
- Tap the FAB
- Tap the input field
- Type e.g. "Hahn" (or "Sülz")
- Try scrolling the overflowing menu

**Expected behavior**
Like in landscape mode, the location proposals menu should be scrollable.

**Environment:**
 - App version: 2.1 from F-Droid
 - Android version: stock Fairphone v10, no changes other than updating GMS and webview
 - Device: Fairphone 3

**Comment by woheller69** [comment]
I think that should be gone with the next version which is not published yet. After 3s of no typing the keyboard is closed

**Comment by uli-on** [comment]
This is fixed now, great, thanks!
