### ISSUE TITLE
Widgets on screen with lower resolution not shown correctly

### ISSUE THREAD

**Issue by jojumaxx** [woheller69/omweather#64]
First of all: thank you! This app and its widgets are great.
I have a Volla Phone X23 which has a screen resolution of 1560x720 px.
The widgets are not shown correctly (but are usable). The larger widget's contents are pushed into each other a bit and the smaller widget doesn't show the minimum temperatures. That doesn't change even if I pull the widgets in length and give them one more row.
I added a screenshot.
I have the same arrangement on a phone with higher resolution where the widgets are shown correctly.
That's why I think this is related to the resolution.
It would be great, if the widgets were shown correctly on a lower resolution screen.
Thanks for taking notice of that.

![Screenshot_20231122-162212_Trebuchet](https://github.com/woheller69/omweather/assets/75417001/56f69c9d-ae3e-40a2-8111-8cf3aaacab9c)

**Comment by woheller69** [comment]
did you set a high screen zoom in Android settings?
But it should always work when resizing the widget. No idea what I could do.
For the 5 day forecast there should also be the min temperatures.
My old Moto G3 has just 1280x720px and works well at all screen zoom levels...

**Comment by jojumaxx** [comment]
I didn't change the zoom setting, it's set to "off". Then I was apparently wrong about the resolution being the reason and it seems to be an issue of my phone or OS.

Maybe I'll find the reason. If so, I'll let you know. Now, that you're aware of this issue, maybe you can keep an eye open, too.

Thank you for responding so quickly.

**Comment by woheller69** [comment]
There is nothing I can do and nobody else seems to be affected
