### ISSUE TITLE
GUI freezes when opened

### ISSUE THREAD

**Issue by niccokunzmann** [woheller69/omweather#65]
**Describe the bug**

When I click on the wheather widget, the GUI opens to show more detail.
Either immediately or after a few seconds, the GUI freezes and cannot be used any more.

**How to Reproduce**
1. Go to home screen
2. Click on the widget
3. Scroll around
4. After a short while the GUI freezes

**Expected behavior**

I would like the GUI to be responsive

**Screenshots**

**Environment (please complete the following information):**
 - App version: 2.1
 - Android version: [e.g. 10]
 - Device: Galaxy A12

My Internet connection is very slow. The freez is sometimes long, sometimes very short but there.

**Comment by woheller69** [comment]
probably your phone is too slow. There is a lot of data to be processed. Try reducing the number of forecast days

**Comment by niccokunzmann** [comment]
The processing could happen outside of the GUI.

**Comment by woheller69** [comment]
I moved the httpRequest and data processing to separate threads.
Please try if that works better for you and let me know.

Uninstall
Remove .zip and install
[app-release.apk.zip](https://github.com/woheller69/omweather/files/13451458/app-release.apk.zip)

**Comment by woheller69** [comment]
I tried it on a slow device and am not convinced. It is different but not better. So I will not make this change.
The best solution on slow devices is probably using the widget. Then new data processing happens in background and not when opening the app.

**Comment by woheller69** [comment]
Should be a bit faster in next release V2.4.  According to Open-Meteo API changes there is less data to evaluate
