### ISSUE TITLE
widget forgets its state

### ISSUE THREAD

**Issue by niccokunzmann** [woheller69/omweather#66]
**Describe the bug**

the widget shows no daca but there was data before.

**How to Reproduce**

**Expected behavior**

In case an update fails, I would like to see the old forecast.

**Screenshots**

![Screenshot_20231123-082612_Launcher](https://github.com/woheller69/omweather/assets/564768/a6407d1f-178d-4189-b600-e1bd7cb1440e)

**Environment (please complete the following information):**
 - App version: 2.1
 - Android version: [e.g. 10]
 - Device: Galaxy A12

**Comment by woheller69** [comment]
not possible. old forecasts are deleted from database when new data is processed
