### ISSUE TITLE
[Enhancement Request] add pinch to zoom into the Diagramm

### ISSUE THREAD

**Issue by Mannshoch** [woheller69/omweather#67]
add pinch to zoom into the Diagramm to zoom into singel days and save the zoom level.
This Diagramm would be nice to have as Widget.

**Comment by woheller69** [comment]
this is not supported by the used library. And this diagram only uses daily and not hourly values. So it only gives a rough overview on what is coming...

**Comment by Mannshoch** [comment]
I like this kind of diagram. Could you please create this diagram for smaler priods than daily, for the timerange you have data.
soething like:
https://search.ch/meteo/untervaz
