### ISSUE TITLE
temp data current projected 7-12c off

### ISSUE THREAD

**Issue by galenthurber** [woheller69/omweather#68]
**Describe the bug**
Comparing with 3 sheltered thermometers, 2 vehicle thermometers, current & projected temps are from 7-12 off
Global grid fn96

Locations are proper, plus manually set nearby 
**How to Reproduce**
1. Go to '...' Widget or main
2. Click on '....' Refresh update
4. See error, wrong temps

**Expected behavior**
Proper readings temperature

**Screenshots**

**Environment (please complete the following information):**
 - App version: [e.g. v1.6] 2.2
 -  
 - Android version: [e.g. 10] 9
 - Device: [e.g. Google Pixel 4] moto g6 play

**Comment by woheller69** [comment]
if weather data is wrong please report to open-meteo
