### ISSUE TITLE
[FR] per hour UV index

### ISSUE THREAD

**Issue by foxjaw** [woheller69/omweather#69]
A regular AccuWeather user here. It shows UV index per hour too.  
I'm new to this app. Any way to see this ?

**Comment by woheller69** [comment]
No, hourly UV index is not available from Open-Meteo, and I also do not want to overload the app with data.
The UV index for the day is available, also in the widget

**Comment by woheller69** [comment]
OpenWeatherMap is not open source. "Open" is just marketing in this case

**Comment by woheller69** [comment]
UV index is also there for every day in the forecast. Just not hourly
