### ISSUE TITLE
Can not  the new Clock widget 

### ISSUE THREAD

**Issue by jolinux** [woheller69/omweather#71]
Hello, nice tool.
Q.: Can not find the new Clock-Widget
 
[omweather](https://github.com/woheller69/omweather/tree/master)/[app](https://github.com/woheller69/omweather/tree/master/app)/[src](https://github.com/woheller69/omweather/tree/master/app/src)/[main](https://github.com/woheller69/omweather/tree/master/app/src/main)/[res](https://github.com/woheller69/omweather/tree/master/app/src/main/res)/[drawable-nodpi](https://github.com/woheller69/omweather/tree/master/app/src/main/res/drawable-nodpi)

/weather_digital_clock_widget_preview.png

I have install from f-droid the version 2.4. Check the Version with menu "(Info) Über"  this Page tell me 

omWeather 
Version 2.4

But at the Page  "Wetter" I fount the old  widgets and no new Clock-Widget.

Is there any problem with your version-control.  Master -> version 2.4  (or current development) ?

Nice day
Jörg

**Comment by woheller69** [comment]
omWeather or weather (=RadarWeather)
Both have the new widget.

Just tested omWeather 2.4 from F-Droid. Widget us there...

**Comment by woheller69** [comment]
What is Page "Wetter"?

Long click home screen, widgets, omWeather, select widget
