### ISSUE TITLE
Inaccurate temperature forecast

### ISSUE THREAD

**Issue by jackthebean** [woheller69/omweather#72]
omWeather 2.4 on Android 10
I appreciate that weather forecasting is a science mixed with an art and don't expect one forecaster's predictions to exactly match another's but find it interesting/curious that the temperature forecast for my area seems to almost always be 4-5C colder than either the UK Met Office or the BBC's weather provider.  On top of this the actual temperature almost always seems to be much closer to the BBC/Met forecast than OmWeather's.

See attached screenshots from 2 separate days for the same location.
![Screenshot_20231219_230112_org woheller69 omweather](https://github.com/woheller69/omweather/assets/9907054/cf25f933-eedf-44b4-a8a2-d72a9bcabe6a)
![Screenshot_20231219_230129_uk gov metoffice weather android](https://github.com/woheller69/omweather/assets/9907054/6e6910cf-40c6-43e4-a6d1-ef83f5daa7b1)
![Screenshot_20231219_230142_com brave browser](https://github.com/woheller69/omweather/assets/9907054/9115c896-b181-4b50-b68b-0dcb7d280b53)
![Screenshot_20231221_084815_uk gov metoffice weather android](https://github.com/woheller69/omweather/assets/9907054/cfcef49d-77fa-4ad2-bf0f-3d0bea0167a4)
![Screenshot_20231221_084822_org woheller69 omweather](https://github.com/woheller69/omweather/assets/9907054/67089b71-e186-489d-bf00-4896dbb9be97)
![Screenshot_20231221_084845_com brave browser](https://github.com/woheller69/omweather/assets/9907054/a9ce0e74-2ac8-457e-aa0a-7f47664de625)

I hope this is helpful,
thanks,

**Comment by woheller69** [comment]
you can discuss such issues on open-meteo.
https://github.com/open-meteo/open-meteo
There is nothing I can do about that.
