### ISSUE TITLE
Bypasses configured proxy

### ISSUE THREAD

**Issue by eku** [woheller69/omweather#76]
**Describe the bug**
Using the app behind a proxy results in an error "Das Gerät ist nicht mit dem Internet verbunden". The main gateway logs direct access of the app to the internet.

**How to Reproduce**
1. Configure WLAN profile with proxy
2. Do not allow direct internet acces on the network gateway
4. Start app and refresh
5. See error

**Expected behavior**
The app uses the configure WLAN proxy.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - App version: 2.5
 - Android version: LOS 20 (AOSP13)
 - Device: 1+ Nord

I can provide a network sniffer log, if needed.

**Comment by woheller69** [comment]
the app needs to ping the internet. So you need to fix it your proxy

**Comment by eku** [comment]
@woheller69 ICMP echo request/reply is not allowed behind  a proxy, only HTTP(S) connection.  That's the idea of a proxy.

Please do not test the connection status in the app yourself, but use the information from Android.

**Comment by woheller69** [comment]
Which information?

**Comment by eku** [comment]
https://developer.android.com/training/monitoring-device-state/connectivity-status-type

**Comment by woheller69** [comment]
That stuff is not reliable

**Comment by eku** [comment]
> That stuff is not reliable

Why not. Just connect to the weather server when Android sends connected callback. If failed, try when app get's callback again. And so on.

As we can see, the ICMP test is even less reliable.

**Comment by woheller69** [comment]
Feel free to implement and test accross a wide range of devices. Then open a PR

**Comment by eku** [comment]
> Feel free to implement and test accross a wide range of devices. Then open a PR

I will replace your app with a different one.

**Comment by eku** [comment]
As far as I understand the code at https://github.com/woheller69/omweather/blob/master/app/src/main/java/org/woheller69/weather/services/UpdateDataService.java#L130 it does a DNS lookup for `api.open-meteo.com`. As the result may already be cached on the device, this is not a reliable test for an existing Internet connection.

The question still remains as to why `omWeather` does not use the proxy configured in the WLAN profile. This could be due to the `com.android.volley` library. 

See 
- https://stackoverflow.com/questions/23914407/volley-behind-a-proxy-server.
- https://gist.github.com/hendrawd/c775d507807e200cfb30f53d6da62c00

Once the cause has been clarified, it should be easy for you to correct the error.

**Comment by woheller69** [comment]
You can simply remove the check and compile your own version.
The currently implemented solution has been working for years over a wide range of devices and Android versions.
Now there is one user where it is not working.
I will not spend time in investigating this and I will not risk a degradation for other users.
