### ISSUE TITLE
[feature] Auto-update when opening the app

### ISSUE THREAD

**Issue by opk12** [woheller69/omweather#81]
**Describe the feature**
What about a checkbox to update the weather prediction automatically, whenever the app is opened?

My use cases
* I set `6 h` + manual update (to save battery), because I do not need the weather prediction on most days. I do not use the widget.
* When I go on a trip, I open the app every hour or so.
* Sometimes the weather changes quickly here. For example, today at 7:00, it predicted slight rain in the morning; at 8:30, it predicted partly cloudy in the morning and rain in the afternoon.
* My sister is not tech-savy and always forgets to tap the Update button. She otherwise likes the app, because it has big icons and a weekly graph.

For clarity: today the app does update automatically, the first time I open it (more than 6 h have passed). When I open again after 2 h, it does not update automatically; it would be convenient if it did.

**Comment by woheller69** [comment]
you can set to 15min if you like. It does not update in background as long as you do not use the widget.

**Comment by opk12** [comment]
Ah yes, now I understand! Thank you.
