### ISSUE TITLE
 [Feature Request] Icon Legend

### ISSUE THREAD

**Issue by maltfield** [woheller69/omweather#83]
This issue will track the feature request to add a "legend" section of the app, that clearly defines each of the icons

## Problem

It's not clear to me which icon means which, or what all the possible icons could be.

For example, there's an icon with a single blue rain drop falling from it. I assume that means the day will have rain. There's also an icon with a cloud and some grey stuff emanating from it. I don't know what that means. I'm also not sure if there exists a cloud with several blue rain drops falling from it, to indicate lots of rain. Or maybe "lots of rain" uses the same icon as the "some rain" icon?

I've clicked around the UI and visited Open-Meteo.com website, but I cannot find a legend that lists all of the icons and their meaning.

## Solution

Under the menu, (either under `About` or under a new button `Legend`, there should be a list of all the icons 1 or more sentences describing what the icon means.

**Comment by woheller69** [comment]
see README

**Comment by maltfield** [comment]
Update: I found a legend here:

 * https://github.com/woheller69/omweather/blob/4857274d8b6f83f4322770e71d0479157168c274/WMO_codes.odt

Note that this does not solve the issue that this information is not available in-app

**Comment by maltfield** [comment]
@woheller69 it looks like the information is still not available in-app. Can you please re-open this issue?

**Comment by woheller69** [comment]
https://github.com/woheller69/omweather/blob/master/README.md

**Comment by maltfield** [comment]
@woheller69 I don't think you understand. Please read the OP.

The solution to this ticket is *not* to provide a legend on the repo. The solution to this ticket is to provide a legend in-app.

Please re-read the OP and re-open this ticket.

**Comment by woheller69** [comment]
this is not planned

**Comment by maltfield** [comment]
> this is not planned

that's fine. If you don't personally plan to implement this feature request, then you can Just tag it as "PR welcome" so that someone else can contribute it.

Please re-open this issue so the feature request won't be buried.

**Comment by Cwpute** [comment]
I kindly request the same feature to have these icons explained in-app and not in the Readme file.
The weather today shows a grey cloud with a flag planted on it, and i don't understand what that means. I'm fine with icons not being instantly understandable (while this can be argued with) but for the.sake of accessibility, please provide an explanation to the users like me who are not developers and don't read the Readme file - most people don't even know it exists !

My preferred solution would be to have a toast message describe the icon when you long-press it (if the explaination is not too long).

**Comment by Cwpute** [comment]
Duplicate of #45
