### ISSUE TITLE
[Feature Request] View History

### ISSUE THREAD

**Issue by maltfield** [woheller69/omweather#84]
This issue is a feature request to view (recent) history of weather in the app.

## Problem

Often an hour passes and I want to know if the weather is going to be worse in the afternoon than it was in the morning, but when I check the app -- the information about the morning is already disappeared!

Also, sometimes I wonder if the amount of rain today is going to be more or less than yesterday -- but the app already has the information about yesterday disappeared!

## Solution

I should be able to, at least, see the weather information from the past 7 days.

**Comment by woheller69** [comment]
This is not planned

**Comment by maltfield** [comment]
@woheller69 can you please re-open this ticket?

If you're not planning to implement it yourself, that's fine. Just tag it with "PR welcome" and leave it open for others to contribute the feature.

Please re-open this issue.
