### ISSUE TITLE
Widget - Optimization

### ISSUE THREAD

**Issue by Machion** [woheller69/omweather#86]
I like the big widget very much (it's beautiful). 
Of course it uses much space and when I shrink it, there are some pixel overlapping or cut off (see screenshots), but maybe it's possible to fix this? 
And btw I find the line with "Weather data by" more or less too much. 

Little feature request: Maybe you can add a little button to switch between locations? 

**Screenshots**
![cirrus1](https://github.com/woheller69/omweather/assets/43423878/d8f1e02e-bdf9-4129-81a5-0049e8ca4a29)
![cirrus2](https://github.com/woheller69/omweather/assets/43423878/e54b499b-dfa0-49ec-971f-5588b65208b8)

**Environment (please complete the following information):**
 - App version: 2.6
 - Android version: 14/LineageOS 21
 - Device: Motorola Moto G100

**Comment by woheller69** [comment]
unfortunately the widgets are dependent on the phone. So you always have to adjust the size until everything is visible.
You can allow GPS for the widget, then it will always adapt to your location.
But it always uses the location in the first tab and I will not change this.

**Comment by Machion** [comment]
Ok what a pity. 
And would you remove the line "Weather data by..."?

**Comment by woheller69** [comment]
that line is needed anyway. "Weather data by..." is replaced by time of next start or end of rain if needed
