### ISSUE TITLE
Rain radar heavily flickering when zooming in our out

### ISSUE THREAD

**Issue by provokateurin** [woheller69/omweather#87]
**Describe the bug**
When zooming in our out on the rain radar there is heavy flickering because all tiles are constantly reloaded. This is very unpleasant to use.

**How to Reproduce**
1. Go to rain radar
2. Zoom in our out

**Expected behavior**
No flickering, tiles should be cached.

**Screenshots**

**Environment (please complete the following information):**
 - App version: 2.6
 - Android version: 14

**Comment by woheller69** [comment]
But that cannot be changed because tiles with different sizes have to be loaded

**Comment by provokateurin** [comment]
Sure, but when I zoom out and then back it, it should load the same tiles as before, no?

**Comment by woheller69** [comment]
Yes, and they are loaded from cache. But there are several layers for map, clouds, radar which require some processing. Using Leaflet library.
https://github.com/Leaflet/Leaflet

**Comment by provokateurin** [comment]
So this would only be fixable inside leaflet?

**Comment by woheller69** [comment]
same with latest Leaflet library.
Maybe some day I will rewrite using  osmdroid instead of leaflet.
Seems to work much better.

**Comment by woheller69** [comment]
For future use:
                //Example for RainViewer radar overlay
                final MapTileProviderBasic RainViewerTileProvider = new MapTileProviderBasic(context);
                final ITileSource RainViewerTileSource = new XYTileSource("RainViewer", 1, 16, 256, "/2/1_1.png", new String[]{"https://tilecache.rainviewer.com/v2/radar/1721157000/256/"});
                RainViewerTileProvider.setTileSource(RainViewerTileSource);
                final TilesOverlay RainviewerTilesOverlay = new TilesOverlay(RainViewerTileProvider, context);
                RainviewerTilesOverlay.setLoadingBackgroundColor(Color.TRANSPARENT);
                holder.map.getOverlays().add(RainviewerTilesOverlay);

**Comment by woheller69** [comment]
Here is a version using Osmdroid. Zooming is better, but now there is a flickering when animating the radar which is not great either. If someone has an idea to fix, let me know. (see also https://github.com/osmdroid/osmdroid/issues/2026)

-Uninstall
-Remove .zip and install
[app-release.apk.zip](https://github.com/user-attachments/files/16279177/app-release.apk.zip)

**Comment by woheller69** [comment]
Got it working without flickering.
Ready to test.
[app-release.apk.zip](https://github.com/user-attachments/files/16323756/app-release.apk.zip)

-Uninstall
-Remove .zip and install

**Comment by provokateurin** [comment]
Just tried it, works perfectly! Thank you so much :heart:
