### ISSUE TITLE
Windspeed forecast issue in certain area?

### ISSUE THREAD

**Issue by twikedk** [woheller69/omweather#89]
**Describe the bug**
Windspeed forecast for Tarm, DK, Central Jutland does not show the same data as on open-meteo.com

**How to Reproduce**
1. Go to 'Manage locations'
2. Click on 'Add locations'
3. Enter 'Tarm'
4. Choose 'Tarm, DK, Central Jutland....'
5. Goto 'Weather'
6. Choose date 2024.07.24

Use this [link](https://open-meteo.com/en/docs#latitude=55.9086&longitude=8.5304&hourly=wind_speed_10m&timezone=Europe%2FBerlin&forecast_days=1&start_date=2024-07-24&end_date=2024-07-24&time_mode=time_interval) for comparison.

**Expected behavior**
The App should show the same data as open-meteo.com API

**Screenshots**
![Screenshot_20240723-115836](https://github.com/user-attachments/assets/a9af9783-3cde-4c39-a92c-2e4d1fe599f4)
![Screenshot_2024-07-23_12-31-06](https://github.com/user-attachments/assets/d21b9d44-1f22-422f-bbbb-e7916797bfb9)

**Environment (please complete the following information):**
 - App version: 2.7
 - Android version: 12
 - Device: Motorola G22

**Comment by woheller69** [comment]
It was a bug on open-meteo

https://github.com/open-meteo/open-meteo/issues/920

**Comment by woheller69** [comment]
should work now. Open-Meteo has fixed the API
