### ISSUE TITLE
Weekly widget is cut off

### ISSUE THREAD

**Issue by thomas2403** [woheller69/omweather#9]
The weekly widget is shown cut off my phone (Oneplus 8T with LineageOS 19.1). After tapping on the widget and open the app, it is normal. But after opening other apps it is getting cut off again.

![IMG_20230304_192533](https://user-images.githubusercontent.com/17723660/222922890-4db541e5-e4fe-46d9-8f0f-a9308b9c117d.jpg)

**Comment by woheller69** [comment]
Just click on it and resize as you like

**Comment by thomas2403** [comment]
OK but still confusing. Then it would take 2 rows, so it is actually 4x2?

**Comment by woheller69** [comment]
That depends on the display and the grid size
