### ISSUE TITLE
Add more units for wind speed

### ISSUE THREAD

**Issue by rma-x** [woheller69/omweather#90]
I suggest to add meters per second (m/s) and knots to the list of units for the wend speed.

**Comment by woheller69** [comment]
You can try it:

-Uninstall
-Remove .zip and install

[app-release.apk.zip](https://github.com/user-attachments/files/16735656/app-release.apk.zip)

**Comment by rma-x** [comment]
Thanks for implementing this so quickly!
I can confirm that it works with the test package.

But it would be nice to have one decimal place for the m/s value (if the values coming from the server have enough granularity for that), at least in the area with the hourly values which has enough horizontal space for two more characters (or three, for wind speeds > 10 m/s).

BTW, are the wind speed values meant as an average or as the maximum gust speed for the given time span (hour or day)?

**Comment by woheller69** [comment]
Wind speed is for the instant according to Open-Meteo docs. I might change to gust for preceeding hour.

**Comment by rma-x** [comment]
Looking again, I think you applied the formula for converting m/s to kn the wrong way around. The knots value has to be about twice the m/s value for the same speed, so you have to divide the m/s value by .51444 instead of multiplying it.

And please let me once more suggest to add a decimal place to the m/s value for better granularity, maybe optionally like you did it for the temperature.
