### ISSUE TITLE
Akku drainage

### ISSUE THREAD

**Issue by Emano-2024** [woheller69/omweather#92]
Since the last update the Akku drainage is inacceptable high.
The Akku manager (LineageOs, Vers. 21, no Google Add ons)
In a screen time oft 3 minutes a drainage rate of 90 %, 
tested again 30 min. later, screen time oft 1 min, drainage rate oft 99%.

**Comment by woheller69** [comment]
There has been no change that would affect power consumption.
Maybe a bug in your akku manager

**Comment by Emano-2024** [comment]
Hello, 
a bug of the Akku manager that shows only problems with cirrus?
I will look at it the next days and weeks.
mfG Eman

Am 23. August 2024 09:23:24 MESZ schrieb woheller69 ***@***.***>:

**Comment by woheller69** [comment]
they often report wrong values esp if you are using the widget
