### ISSUE TITLE
Background of widget

### ISSUE THREAD

**Issue by pilian** [woheller69/omweather#94]
Zunächst mal vielen Dank für die Weiterführung der secuso APP.
Die Anzeige der mm Niederschlag in der Übersicht ist perfekt.
Beim Widget könnte der Hintergrund heller sein.
Außerdem wäre die Anzeige des Niederschlages hilfreich.
VG
![IMG_20240825_180138](https://github.com/user-attachments/assets/0fa8bfac-114d-40d4-8022-a6c9d9c8289d)

**Comment by druk13** [comment]
Ich kann mich dem Dank von pilian nur anschließen und hätte eine Bitte:

Wäre es möglich in die App für den Hintergrund der Widgets einen
- Slider zur Steuerung der Transparenz

und
- der Hintergrundfarbe

einzubauen?

**Comment by woheller69** [comment]
Try this, transparency can be set in settings, color will stay as it is.
[app-release.apk.zip](https://github.com/user-attachments/files/16962453/app-release.apk.zip)

Uninstall
Remove .zip and install

**Comment by druk13** [comment]
Thank's Wolfgang (?) for the promt reaction.

If I switch the slider to the right, middle or back to the left position, there is no change in transperancy of the widget 🤔

**Comment by woheller69** [comment]
it refreshes when the widget updates

**Comment by druk13** [comment]
Exactly! When the slider is in right position, there is no background after a refresh 😊

Thanks a lot for the prompt 🚀 programming task!

Would it be possible that you upload this version to F-Droid?

**Comment by woheller69** [comment]
I no problems come up it will be in the next update
