### ISSUE TITLE
Widgets does not update

### ISSUE THREAD

**Issue by muziofg** [woheller69/omweather#95]
**Describe the bug**

I'm using CIrrus Version 2.9  (from f-droid) on a Lenovo tablet and on a Fairphone (both with Android 14) and on both I've noticed the WeatherWidget5day widget wasn't change day, so I've investigate deeply. Also the WeatherWidget doesn't update accordingly with the specified period. 

**How to Reproduce**
I have tried to set the shortest period available (15 min) and wait multiple time to see the time changing on WeatherWidget (who shows a reference time to the latest update) but nothing happens. 
Also I would expect to see an immediate update after a cold boot (when the period selected has clearly expired) instead it doesn't happen.

Also I've checked the background network traffic of this app and I see too few bytes exchanged, so I think the related service doesn't work correctly

**Expected behavior**

WeatherWidget5day must change days and show updated forecast
WeatherWidget must show updated forecast and the time of the last data fetched accordingly with the settings

**Environment (please complete the following information):**
 - App version: 2.9
 - Android version: 14
 - Device: Fairphone 5, Lenovo Tab M10

Tell me if you need more information or evidence about this bug
Edit:
Could be relevant: I have two locations without GPS enabled

**Comment by woheller69** [comment]
The 5 day widget updates every 6 hours, the other widgets every 30min

The other interval is only valid if you open the app

**Comment by muziofg** [comment]
these details must be cleared in the docs

however, days in the 5 days widget doesn't change... for days

**Comment by woheller69** [comment]
it updates every 6h

**Comment by muziofg** [comment]
Ok, but I've a doubt.
For example if the app on device is scheduling an update on 12am, 06am, 12pm and 06pm,  but the device is powered up between 01pm and 05pm the failure to update is also triggered and retried after a new boot ?

**Comment by woheller69** [comment]
After boot Android updates widgets immediately

**Comment by muziofg** [comment]
this behaviour isn't what I am experienced, let me investigate deeply on a third device 
There are also suggestions about what I can do to debug this strange issue?

**Comment by woheller69** [comment]
For sure there is no issue. This has been working for many years on tons of devices

**Comment by muziofg** [comment]
Sorry, I've checked the issue and it happens only on the tablet

**Comment by woheller69** [comment]
maybe try switching  off battery optimization for this app in Android settings

**Comment by muziofg** [comment]
I always forget who the Adaptive Battery feature exists
thanks
