### ISSUE TITLE
"Problem loading widget" since Version 3.0 (F-Droid)

### ISSUE THREAD

**Issue by AndrewPy** [woheller69/omweather#98]
**Describe the bug**
Since version 3.0, the widgets no longer work.
They now only display "Problem loading widget".

**How to Reproduce**
1. Install Cirrus 3.0.
2. Add a location in the settings.
3. Add the widget to the android launcher.
4. See error "Problem loading widget".

**Expected behavior**
The widget should display the weather information.

**Environment (please complete the following information):**
 - App version: 3.0
 - Android version: Android 10 and Lineage 16
 - Device: tested on different devices (with Ruthless Launcher and Trebuchet Launcher)

**Comment by woheller69** [comment]
Only on old devices. Already fixed in V3.1
