### ISSUE TITLE
Display error

### ISSUE THREAD

**Issue by ralv3967** [woheller69/omweather#99]
**Describe the bug**
Just a small visual error: in the weekly view, the fields per day could be a bit wider. With 4 forecast days, the width of the display is not fully utilized, and with more than 4 days, a bit of the 5th day appears at the edge.

![Screenshot_20240922-065955](https://github.com/user-attachments/assets/4f236ee1-52dd-4371-8214-377fa1943834)

**Environment (please complete the following information):**
 - App version: 3.0
 - Android version: 14
 - Device: Google Pixel 7

**Comment by woheller69** [comment]
That depends on your screen size, font size, etc.
I have full 5 days on my display.
Nothing I can change...
